name: Build and Push PHP-Apache Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 19 * * *' # Runs daily at 7 PM UTC / Midnight Pakistan time
  workflow_dispatch:      # Allows manual triggering from GitHub UI

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate tag
        id: vars
        run: echo "TAG=$(date +'%Y%m%d')" >> "$GITHUB_OUTPUT"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag asimzeeshan/php:8.4-apache:latest

      # - name: Build and Push Docker Image
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     push: true
      #     tags:  |
      #       asimzeeshan/php:8.4-apache:latest
      #       asimzeeshan/php:8.4-apache:${{ steps.vars.outputs.TAG }}
